### ISSUE TITLE
Task fails with error "--local can only be used inside a git repository"

### ISSUE THREAD

**Issue by fabian-schwarz** [mlarhrouch/azure-pipeline-gpt-pr-review#25]
The tasks errors out in my pipeline with the error message :
```bash
##[error]fatal: --local can only be used inside a git repository
```

Maybe due to the pipeline checking out more than one repository:
```yaml
- checkout: self
  persistCredentials: true
- checkout: Scripts
```

Probably fixed by making the following line configurable: https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/blob/1db7cfa7a1d56f0a58aa4580caace063610b158a/GPTPullRequestReview/src/git.ts#L7
