### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by davidreher** [mlarhrouch/azure-pipeline-gpt-pr-review#61]
Hi,

I tried using the extension, but I get the following:

```
Start reviewing src/config/config.service.ts ...
Only absolute URLs are supported
```

Is this an issue with simple-git? Any ideas?

Thanks in advance,
David

**Comment by 97saundersj** [comment]
@davidreher are you using azure openAI? I wonder if it could be you have an incorrect endpoint configured.

**Comment by davidreher** [comment]
Hmm, I have it set up like this:
```yaml
jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
      name: $(build-pool)
    variables:
      NPM_CACHE_FOLDER: $(System.DefaultWorkingDirectory)/node_modules
    steps:
      - checkout: self
        persistCredentials: true
      <...>
      - task: mustaphalarhrouch.GPTPullRequestReview.GPTPullRequestReview.GPTPullRequestReview@0
        displayName: 'GPTPullRequestReview'
        inputs:
          api_key: $(gptReviewApiKey)
          model: $(gptReviewModel)
          aoi_endpoint: $(gptReviewAoiEndpoint)
```
and my variables are configured like this in a variable group:
```
gptReviewEndpoint: https://xxx.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview
gptReviewModel: gpt-4
gptReviewApiKey: <my api key>
```
